### ISSUE TITLE
Plugin broke with "An error occurred while rendering settings panel."

### ISSUE THREAD

**Issue by stressatoo** [Juby210/bdCompat#46]
Throws error

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at \plugins\bdCompat\components\PluginList.jsx:75:39
    at Array.sort (<anonymous>)
    at PluginList.__getPlugins (\plugins\bdCompat\components\PluginList.jsx:74:20)
    at PluginList.render (\plugins\bdCompat\components\PluginList.jsx:20:26)
    at AsyncComponent.componentDidMount (C:\Users\tryit\powercord\src\fake_node_modules\powercord\components\AsyncComponent.js:12:10)

Component stack:
    at h (https://canary.discord.com/assets/b3a2c063c7294b66372d.js:6259:97)
    at div
    at h (https://canary.discord.com/assets/b3a2c063c7294b66372d.js:6259:97)
    at u (https://canary.discord.com/assets/b3a2c063c7294b66372d.js:4373:598)
    at div
    at p (https://canary.discord.com/assets/21745c109daea8ac7200.js:18:468)
```

Doesn't load any BBD plugin and doesn't render settings panel.

--------------------------

Canary 145048 (c70f9f6)
Host 1.0.49
Windows 11 64-Bit
Powercord v2 (bb30f25)

**Comment by Hampo** [comment]
Same issue - only on some plugins though

**Comment by stressatoo** [comment]
> Same issue - only on some plugins though

None of my plugins work. I'm switching to Replugged now to see if there's any difference.

**Comment by MarOnic12345** [comment]
Same problem here. Switched to Replugged and it didn't help. I'm guessing it's due to an update with 0BDFDB.

**Comment by supahfox** [comment]
Same issue here

**Comment by stressatoo** [comment]
[This](https://github.com/Juby210/bdCompat/issues/45#issue-1358115896) is the current workaround.
Reverting bdCompat's version doesn't break the functionality, but bugs still exist, such as empty plugin names; the plugin will prompt for 0BDFDB's installation several times, but will start working eventually.

![image](https://user-images.githubusercontent.com/60473020/188119639-3c822463-3177-413c-9d3f-605d6ceb32ae.png)

**Comment by checkraisefold** [comment]
> [This](https://github.com/Juby210/bdCompat/issues/45#issue-1358115896) is the current workaround. Reverting bdCompat's version doesn't break the functionality, but bugs still exist, such as empty plugin names; the plugin will prompt for 0BDFDB's installation several times, but will start working eventually.

unfortunately I started getting this current issue with error occured while rendering settings panel waay after I reverted that specific commit locally, seems like a replugged/discord update broke it within the past day
![image](https://user-images.githubusercontent.com/19525688/188141652-534aa393-95b5-4631-ba07-31910541d3ff.png)

**Comment by stressatoo** [comment]
> > [This](https://github.com/Juby210/bdCompat/issues/45#issue-1358115896) is the current workaround. Reverting bdCompat's version doesn't break the functionality, but bugs still exist, such as empty plugin names; the plugin will prompt for 0BDFDB's installation several times, but will start working eventually.
> 
> unfortunately I started getting this current issue with error occured while rendering settings panel waay after I reverted that specific commit locally, seems like a replugged/discord update broke it within the past day ![image](https://user-images.githubusercontent.com/19525688/188141652-534aa393-95b5-4631-ba07-31910541d3ff.png)

A new workaround showed up in [this thread](https://discord.com/channels/1000926524452647132/1014967215214317640) from the [Replugged server](https://discord.gg/zzG5AHeYAp). It seems like replacing 0BDFDB with an [older version](https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/848d3cf1ccaf6c4a222f75fa38f43e0c62434160/Library/0BDFDB.plugin.js) works too.

**Comment by supahfox** [comment]
> > > [This](https://github.com/Juby210/bdCompat/issues/45#issue-1358115896) is the current workaround. Reverting bdCompat's version doesn't break the functionality, but bugs still exist, such as empty plugin names; the plugin will prompt for 0BDFDB's installation several times, but will start working eventually.
> > 
> > 
> > unfortunately I started getting this current issue with error occured while rendering settings panel waay after I reverted that specific commit locally, seems like a replugged/discord update broke it within the past day ![image](https://user-images.githubusercontent.com/19525688/188141652-534aa393-95b5-4631-ba07-31910541d3ff.png)
> 
> A new workaround showed up in [this thread](https://discord.com/channels/1000926524452647132/1014967215214317640) from the [Replugged server](https://discord.gg/zzG5AHeYAp). It seems like replacing 0BDFDB with an [older version](https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/848d3cf1ccaf6c4a222f75fa38f43e0c62434160/Library/0BDFDB.plugin.js) works too.

Worked perfectly thanks

**Comment by ghost** [comment]
> > > > [This](https://github.com/Juby210/bdCompat/issues/45#issue-1358115896) is the current workaround. Reverting bdCompat's version doesn't break the functionality, but bugs still exist, such as empty plugin names; the plugin will prompt for 0BDFDB's installation several times, but will start working eventually.
> > > 
> > > 
> > > unfortunately I started getting this current issue with error occured while rendering settings panel waay after I reverted that specific commit locally, seems like a replugged/discord update broke it within the past day ![image](https://user-images.githubusercontent.com/19525688/188141652-534aa393-95b5-4631-ba07-31910541d3ff.png)
> > 
> > 
> > A new workaround showed up in [this thread](https://discord.com/channels/1000926524452647132/1014967215214317640) from the [Replugged server](https://discord.gg/zzG5AHeYAp). It seems like replacing 0BDFDB with an [older version](https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/848d3cf1ccaf6c4a222f75fa38f43e0c62434160/Library/0BDFDB.plugin.js) works too.
> 
> Worked perfectly thanks

Is this gonna be fixed tho? Or we have to keep BDFDB not updated forever?

**Comment by stressatoo** [comment]
> Is this gonna be fixed tho? Or we have to keep BDFDB not updated forever?

Unfortunately I don't have enough knowledge to submit a fixing PR. I guess the devs will fix that.

**Comment by lordcyb3r** [comment]
> > > > > [This](https://github.com/Juby210/bdCompat/issues/45#issue-1358115896) is the current workaround. Reverting bdCompat's version doesn't break the functionality, but bugs still exist, such as empty plugin names; the plugin will prompt for 0BDFDB's installation several times, but will start working eventually.
> > > > 
> > > > 
> > > > unfortunately I started getting this current issue with error occured while rendering settings panel waay after I reverted that specific commit locally, seems like a replugged/discord update broke it within the past day ![image](https://user-images.githubusercontent.com/19525688/188141652-534aa393-95b5-4631-ba07-31910541d3ff.png)
> > > 
> > > 
> > > A new workaround showed up in [this thread](https://discord.com/channels/1000926524452647132/1014967215214317640) from the [Replugged server](https://discord.gg/zzG5AHeYAp). It seems like replacing 0BDFDB with an [older version](https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/848d3cf1ccaf6c4a222f75fa38f43e0c62434160/Library/0BDFDB.plugin.js) works too.
> > 
> > 
> > Worked perfectly thanks
> 
> Is this gonna be fixed tho? Or we have to keep BDFDB not updated forever?

there is a way to trick the plugin into not prompting you to update. first get this old version: https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/848d3cf1ccaf6c4a222f75fa38f43e0c62434160/Library/0BDFDB.plugin.js

than replace line 22 ("version": "2.5.2",) with ("version": "2.5.9",) and reload discord. This is at least a solution to remove the nag. you will have to replace that version string whenever there is a new update. here is the plugin file i modified in the event you dont want to do the modification your self: https://cdn.discordapp.com/attachments/194952965726011392/1021092611647348828/0BDFDB.plugin.js
